### ISSUE TITLE
js error

### ISSUE THREAD

**Issue by chronolai** [Amobe/Amobe.github.io#1]
querySelector 出來的東西應該沒有 addWord 

![image](https://user-images.githubusercontent.com/729288/135042994-51e396bb-bf1e-4642-b7e4-c323d59d2f41.png)
![image](https://user-images.githubusercontent.com/729288/135043011-348c5745-35c6-47eb-a690-c5f235d86c5d.png)

**Comment by Amobe** [comment]
Forward to https://github.com/Amobe/JPTrain/issues/1
